# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graphjin < Formula
  desc "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler."
  homepage "https://graphjin.com"
  version "3.18.28"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dosco/graphjin/releases/download/v3.18.28/graphjin_3.18.28_darwin_amd64.tar.gz"
      sha256 "f6783d9de2ec4edf3bbc6f22bca4a41dde6e1a25538e463e153cb2d4b0afb418"

      define_method(:install) do
        bin.install "graphjin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dosco/graphjin/releases/download/v3.18.28/graphjin_3.18.28_darwin_arm64.tar.gz"
      sha256 "81d3f68be1dce7883b10faa6583ac3e8aadb28f1d2d8fe8cd9177781f999f766"

      define_method(:install) do
        bin.install "graphjin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dosco/graphjin/releases/download/v3.18.28/graphjin_3.18.28_linux_amd64.tar.gz"
      sha256 "310df3d959d4f149bb98a2f76ae8cdb5f6ad72e91ee125faa929e09bf9727d24"
      define_method(:install) do
        bin.install "graphjin"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dosco/graphjin/releases/download/v3.18.28/graphjin_3.18.28_linux_armv6.tar.gz"
      sha256 "91b4aabd98ffcfb7077f66b4f74532875f91971d23ae66fce5c12a9797be9087"
      define_method(:install) do
        bin.install "graphjin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dosco/graphjin/releases/download/v3.18.28/graphjin_3.18.28_linux_arm64.tar.gz"
      sha256 "ba946f52d4667963aa1b25a21dc63841ac496da0b528cb4cb1462022b2de0c83"
      define_method(:install) do
        bin.install "graphjin"
      end
    end
  end
end
